# Livro para consulta:
- https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html
- https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [52]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [53]:
sinasc_raw = pd.read_csv('SINASC_RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

# Tarefa 2

### 1. Crie 2 faixas de Latitude do município (munResLat) sendo uma acima e outra abaixo de -10.5 e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [78]:
# Cria as faixas de latitude
sinasc_raw["faixa_latitude"] = pd.cut(
    sinasc_raw["munResLat"],
    bins=[-float("inf"), -10.5, float("inf")],
    labels=["Abaixo de -10.5", "Acima de -10.5"]
)

# Seleciona as variáveis numéricas que ainda não foram usadas:
variaveis = ["PESO", "APGAR1"]

# Realiza o groupby e calcula as estatísticas solicitadas
resultado = (
    sinasc_raw
    .groupby("faixa_latitude")[variaveis]
    .agg(["sum", "mean", "min", "max", "median", "std", "var"])
    .round(2)
)

resultado

C:\Users\brunn\AppData\Local\Temp\ipykernel_30556\4123695945.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("faixa_latitude")[variaveis]

                     PESO                                                 \
                      sum     mean  min   max  median     std        var
faixa_latitude
Abaixo de -10.5  40076866  3242.20  258  5985  3270.0  532.25  283294.87
Acima de -10.5   45194485  3245.56  295  5190  3275.0  557.40  310696.02

                   APGAR1
                      sum  mean  min   max median   std  var
faixa_latitude
Abaixo de -10.5   99563.0  8.07  0.0  10.0    8.0  0.95  0.9
Acima de -10.5   113674.0  8.20  0.0  10.0    8.0  1.00  1.0

### 2. Crie 2 faixas da área dos municípios (munResArea) sendo uma acima e outra abaixo de 3000 e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [55]:
# Cria as faixas de área do município
sinasc_raw["faixa_area"] = pd.cut(
    sinasc_raw["munResArea"],
    bins=[-float("inf"), 3000, float("inf")],
    labels=["Abaixo de 3000", "Acima de 3000"]
)

# Escolhe duas variáveis numéricas ainda não utilizadas
variaveis = ["IDADEPAI", "APGAR5"]

# Agrupa pelas faixas e calcula as estatísticas pedidas
resultado_area = (
    sinasc_raw
    .groupby("faixa_area")[variaveis]
    .agg(["sum", "mean", "min", "max", "median", "std", "var"])
    .round(2)
)

resultado_area

C:\Users\brunn\AppData\Local\Temp\ipykernel_30556\1179712627.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("faixa_area")[variaveis]

                IDADEPAI                                           APGAR5  \
                     sum   mean   min   max median   std    var       sum
faixa_area
Abaixo de 3000   78074.0  31.09  16.0  69.0   30.0  7.68  58.91   47560.0
Acima de 3000   158424.0  31.09  15.0  86.0   30.0  7.82  61.13  199579.0


                mean  min   max median   std   var
faixa_area
Abaixo de 3000  9.13  0.0  10.0    9.0  0.80  0.64
Acima de 3000   9.19  0.0  10.0    9.0  0.79  0.62

### 3. Determine faixas na variável munResAlt e aplique o groupby usando essas faixas como chave e realize operações de soma, media, minimo, maximo, mediana, desvio padrao, variancia pra pelo menos 2 variáveis numéricas ainda não utilizadas

In [56]:
sinasc_raw["munResAlt"].describe()

count    27027.000000
mean       179.111999
std        123.138365
min         85.000000
25%         87.000000
50%        153.000000
75%        191.000000
max        595.000000
Name: munResAlt, dtype: float64

A análise da variável **munResAlt** mostra que a maioria dos municípios está em altitudes abaixo de 200 m, com poucos casos chegando a 600 m, indicando uma distribuição assimétrica. Por isso, as faixas foram definidas em três níveis: baixa altitude (até 150 m), média altitude (150–300 m) e alta altitude (acima de 300 m), refletindo melhor a variação observada nos dados.

In [57]:
# Cria faixas de altitude com base na distribuição dos dados
sinasc_raw["faixa_altitude"] = pd.cut(
    sinasc_raw["munResAlt"],
    bins=[-float("inf"), 150, 300, float("inf")],
    labels=["Baixa", "Média", "Alta"]
)

# Escolhe duas variáveis numéricas ainda não utilizadas
variaveis = ["QTDFILVIVO", "IDADEMAE"]

# Calcula estatísticas
resultado_alt = (
    sinasc_raw
    .groupby("faixa_altitude")[variaveis]
    .agg(["sum", "mean", "min", "max", "median", "std", "var"])
    .round(2)
)

resultado_alt

C:\Users\brunn\AppData\Local\Temp\ipykernel_30556\315218462.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("faixa_altitude")[variaveis]

               QTDFILVIVO                                     IDADEMAE         \
                      sum  mean  min   max median   std   var      sum   mean
faixa_altitude
Baixa             13365.0  1.17  0.0  14.0    1.0  1.27  1.62   327931  26.01
Média             11186.0  0.97  0.0  30.0    1.0  1.07  1.15   311900  26.14
Alta               2275.0  0.92  0.0  10.0    1.0  1.06  1.12    65406  26.30


               min max median   std    var
faixa_altitude
Baixa           11  47   25.0  6.52  42.47
Média           12  53   26.0  6.25  39.10
Alta            13  53   26.0  6.36  40.43

### 4. Plote no mesmo grafico ao longo do tempo a idade media das mulheres de cada regiao imediatas de rondonia

In [58]:
imediatas = {
    "Candeias do Jamari": "Porto Velho",
    "Guajará-Mirim": "Porto Velho",
    "Itapuã do Oeste": "Porto Velho",
    "Nova Mamoré": "Porto Velho",
    "Porto Velho": "Porto Velho",
    "Ariquemes": "Ariquemes",
    "Alto Paraíso": "Ariquemes",
    "Buritis": "Ariquemes",
    "Cacaulândia": "Ariquemes",
    "Campo Novo de Rondônia": "Ariquemes",
    "Cujubim": "Ariquemes",
    "Monte Negro": "Ariquemes",
    "Rio Crespo": "Ariquemes",
    "Jaru": "Jaru",
    "Governador Jorge Teixeira": "Jaru",
    "Machadinho D'Oeste": "Jaru",
    "Theobroma": "Jaru",
    "Vale do Anari": "Jaru",
    "Alvorada D'Oeste": "Ji-Paraná",
    "Costa Marques": "Ji-Paraná",
    "Ji-Paraná": "Ji-Paraná",
    "Mirante da Serra": "Ji-Paraná",
    "Nova União": "Ji-Paraná",
    "Ouro Preto do Oeste": "Ji-Paraná",
    "Presidente Médici": "Ji-Paraná",
    "São Francisco do Guaporé": "Ji-Paraná",
    "São Miguel do Guaporé": "Ji-Paraná",
    "Seringueiras": "Ji-Paraná",
    "Teixeirópolis": "Ji-Paraná",
    "Urupá": "Ji-Paraná",
    "Vale do Paraíso": "Ji-Paraná",
    "Cacoal": "Cacoal",
    "Alta Floresta D'Oeste": "Cacoal",
    "Alto Alegre dos Parecis": "Cacoal",
    "Castanheiras": "Cacoal",
    "Espigão D'Oeste": "Cacoal",
    "Ministro Andreazza": "Cacoal",
    "Nova Brasilândia D'Oeste": "Cacoal",
    "Novo Horizonte do Oeste": "Cacoal",
    "Parecis": "Cacoal",
    "Pimenta Bueno": "Cacoal",
    "Primavera de Rondônia": "Cacoal",
    "Rolim de Moura": "Cacoal",
    "Santa Luzia D'Oeste": "Cacoal",
    "São Felipe D'Oeste": "Cacoal",
    "Vilhena": "Vilhena",
    "Cabixi": "Vilhena",
    "Cerejeiras": "Vilhena",
    "Chupinguaia": "Vilhena",
    "Colorado do Oeste": "Vilhena",
    "Corumbiara": "Vilhena",
    "Pimenteiras do Oeste": "Vilhena"
}

In [59]:
sinasc_raw["DTNASC"] = pd.to_datetime(sinasc_raw["DTNASC"], errors="coerce")
sinasc_raw["DTNASC"].dt.year.value_counts().sort_index()

DTNASC
2019    27028
Name: count, dtype: int64

Como todos os registros disponíveis são de 2019, optei por não gerar um gráfico temporal — ele não mostraria variação ao longo do tempo. Em vez disso, o código adiciona uma coluna de região imediata com base no dicionário fornecido, agrupa os dados por essa região e calcula a média da idade das mães em cada uma delas. Após remover valores nulos e arredondar os resultados, exibos os valores em formato de tabela, o que permite comparar diretamente as regiões sem necessidade de visualização gráfica.

In [60]:
# Mapeia cada município à sua região imediata
sinasc_raw["regiao_imediata"] = sinasc_raw["munResNome"].map(imediatas)

# Calcula a idade média das mães por região imediata
idade_media_regiao = (
    sinasc_raw.groupby("regiao_imediata")["IDADEMAE"]
    .mean()
    .reset_index()
    .dropna()
    .sort_values("IDADEMAE", ascending=False)
    .round(2)
)

# Mostra o resultado em formato de tabela
idade_media_regiao

  regiao_imediata  IDADEMAE
5         Vilhena     26.42
1          Cacoal     26.35
4     Porto Velho     26.17
3       Ji-Paraná     26.09
2            Jaru     25.71
0       Ariquemes     25.46

### 5. Utilize a tabela do link abaixo e crie faixas utilizando o mapping e gere agrupamentos utilizando essas faixas como chave

### 5.1 IDH
A - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_IDH-M

In [61]:
print(sinasc_raw.columns)

Index(['ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE', 'ESTCIVMAE',
       'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT', 'CODMUNRES',
       'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC', 'HORANASC',
       'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL', 'DTCADASTRO',
       'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM', 'DIFDATA',
       'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU', 'ESCMAE2010',
       'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT', 'QTDPARTNOR',
       'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC', 'TPMETESTIM',
       'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART', 'STCESPARTO',
       'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC', 'ESCMAEAGR1',
       'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON', 'PARIDADE',
       'KOTELCHUCK', 'CONTADOR', 'munResStatus', 'munResTipo', 'munResNome',
       'munResUf', 'munResLat', 'munResLon', 'munResAlt', 'munResArea',
       'faixa_latitude', 'faixa_area', 'faixa_altitude', 'regiao_imediata'],
      dtype='object')

In [62]:
# Crio um dicionário com IDH aproximado de cada município de Rondônia (dados do link acima - Wikipédia)

idh_dict = {
    "Alta Floresta D'Oeste": 0.685,
    "Ariquemes": 0.700,
    "Cabixi": 0.681,
    "Cacoal": 0.718,
    "Cerejeiras": 0.708,
    "Colorado do Oeste": 0.700,
    "Corumbiara": 0.668,
    "Costa Marques": 0.647,
    "Espigão D'Oeste": 0.705,
    "Guajará-Mirim": 0.708,
    "Jaru": 0.700,
    "Ji-Paraná": 0.710,
    "Machadinho D'Oeste": 0.660,
    "Nova Brasilândia D'Oeste": 0.684,
    "Ouro Preto do Oeste": 0.713,
    "Pimenta Bueno": 0.708,
    "Porto Velho": 0.736,
    "Presidente Médici": 0.699,
    "Rolim de Moura": 0.702,
    "Santa Luzia D'Oeste": 0.676,
    "Vilhena": 0.731,
    "São Miguel do Guaporé": 0.676,
    "Alvorada D'Oeste": 0.677,
    "Candeias do Jamari": 0.670,
    "Cujubim": 0.658,
    "Novo Horizonte do Oeste": 0.689,
    "Buritis": 0.675,
    "Alto Paraíso": 0.673,
    "Monte Negro": 0.667,
    "Seringueiras": 0.657,
    "Campo Novo de Rondônia": 0.665,
    "Vale do Anari": 0.659,
    "Vale do Paraíso": 0.667,
    "Theobroma": 0.656,
    "São Francisco do Guaporé": 0.684,
    "Governador Jorge Teixeira": 0.656,
    "Cacaulândia": 0.665,
    "Ministro Andreazza": 0.677,
    "Parecis": 0.673,
    "Primavera de Rondônia": 0.677,
    "Rio Crespo": 0.663,
    "Teixeirópolis": 0.672,
    "Mirante da Serra": 0.680,
    "Nova Mamoré": 0.672,
    "Pimenteiras do Oeste": 0.688,
    "Chupinguaia": 0.670,
    "Alto Alegre dos Parecis": 0.676,
    "Castanheiras": 0.673,
}

In [79]:
# Cria coluna com o valor numérico do IDH
sinasc_raw["IDH"] = sinasc_raw["munResNome"].map(idh_dict)

# Cria a faixa de classificação do IDH (Muito baixo → Muito alto)
sinasc_raw["faixa_IDH"] = pd.cut(
    sinasc_raw["IDH"],
    bins=[0, 0.499, 0.599, 0.699, 0.799, 1.0],
    labels=["Muito baixo", "Baixo", "Médio", "Alto", "Muito alto"]
)

# Remove linhas com IDH ausente diretamente no DataFrame original
sinasc_raw.dropna(subset=["IDH", "faixa_IDH"], inplace=True)

# Exibe apenas as novas colunas adicionadas para conferência
print("Colunas adicionadas ao DataFrame original:\n")
print(sinasc_raw[["munResNome", "IDH", "faixa_IDH"]].drop_duplicates().sort_values("IDH"))

Colunas adicionadas ao DataFrame original:

                      munResNome    IDH faixa_IDH
198                Costa Marques  0.647     Médio
736    Governador Jorge Teixeira  0.656     Médio
3068                   Theobroma  0.656     Médio
1801                Seringueiras  0.657     Médio
73                       Cujubim  0.658     Médio
174                Vale do Anari  0.659     Médio
259           Machadinho D'Oeste  0.660     Médio
119                   Rio Crespo  0.663     Médio
200       Campo Novo de Rondônia  0.665     Médio
125                  Cacaulândia  0.665     Médio
77                   Monte Negro  0.667     Médio
3566             Vale do Paraíso  0.667     Médio
517                   Corumbiara  0.668     Médio
2132                 Chupinguaia  0.670     Médio
178           Candeias do Jamari  0.670     Médio
360                  Nova Mamoré  0.672     Médio
3558               Teixeirópolis  0.672     Médio
1401                     Parecis  0.673     Médio
2067                Castanheiras  0.673     Médio
75                  Alto Paraíso  0.673     Médio
138                      Buritis  0.675     Médio
3        Alto Alegre dos Parecis  0.676     Médio
594        São Miguel do Guaporé  0.676     Médio
1782       Primavera de Rondônia  0.677     Médio
1427          Ministro Andreazza  0.677     Médio
1087            Mirante da Serra  0.680     Médio
11425                     Cabixi  0.681     Médio
1411    São Francisco do Guaporé  0.684     Médio
1509    Nova Brasilândia D'Oeste  0.684     Médio
0          Alta Floresta D'Oeste  0.685     Médio
4045        Pimenteiras do Oeste  0.688     Médio
6        Novo Horizonte do Oeste  0.689     Médio
1292           Presidente Médici  0.699     Médio
348            Colorado do Oeste  0.700      Alto
83                          Jaru  0.700      Alto
72                     Ariquemes  0.700      Alto
21                Rolim de Moura  0.702      Alto
1406             Espigão D'Oeste  0.705      Alto
1194                  Cerejeiras  0.708      Alto
839                Pimenta Bueno  0.708      Alto
2555               Guajará-Mirim  0.708      Alto
132                    Ji-Paraná  0.710      Alto
435          Ouro Preto do Oeste  0.713      Alto
1381                      Cacoal  0.718      Alto
141                      Vilhena  0.731      Alto
123                  Porto Velho  0.736      Alto

### 5.2 IFDM
B - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_IFDM

In [64]:
# Dicionário com valores de IFDM para municípios de Rondônia
ifdm_dict = {
    "Alta Floresta D'Oeste": 0.579,
    "Ariquemes": 0.623,
    "Cabixi": 0.568,
    "Cacoal": 0.654,
    "Cerejeiras": 0.613,
    "Colorado do Oeste": 0.607,
    "Corumbiara": 0.541,
    "Costa Marques": 0.552,
    "Espigão D'Oeste": 0.635,
    "Guajará-Mirim": 0.611,
    "Jaru": 0.612,
    "Ji-Paraná": 0.645,
    "Machadinho D'Oeste": 0.593,
    "Nova Brasilândia D'Oeste": 0.589,
    "Ouro Preto do Oeste": 0.639,
    "Pimenta Bueno": 0.647,
    "Porto Velho": 0.674,
    "Presidente Médici": 0.599,
    "Rolim de Moura": 0.648,
    "Santa Luzia D’Oeste": 0.606,
    "Vilhena": 0.671,
    "São Miguel do Guaporé": 0.603,
    "Alvorada D’Oeste": 0.602,
    "Candeias do Jamari": 0.590,
    "Cujubim": 0.576,
    "Novo Horizonte do Oeste": 0.628,
    "Buritis": 0.601,
    "Alto Paraíso": 0.598,
    "Monte Negro": 0.599,
    "Seringueiras": 0.575,
    "Campo Novo de Rondônia": 0.587,
    "Vale do Anari": 0.579,
    "Vale do Paraíso": 0.599,
    "Theobroma": 0.574,
    "São Francisco do Guaporé": 0.589,
    "Governador Jorge Teixeira": 0.573,
    "Cacaulândia": 0.587,
    "Ministro Andreazza": 0.601,
    "Parecis": 0.598,
    "Primavera de Rondônia": 0.601,
    "Rio Crespo": 0.586,
    "Teixeirópolis": 0.597,
    "Mirante da Serra": 0.613,
    "Nova Mamoré": 0.610,
    "Pimenteiras do Oeste": 0.627,
    "Chupinguaia": 0.590,
    "Alto Alegre dos Parecis": 0.602,
    "Castanheiras": 0.598
}

In [65]:
# Adiciona a coluna com valor numérico de IFDM
sinasc_raw["IFDM"] = sinasc_raw["munResNome"].map(ifdm_dict)

# Cria coluna com categoria textual baseada no IFDM
sinasc_raw["faixa_IFDM"] = pd.cut(
    sinasc_raw["IFDM"],
    bins=[0.0, 0.4, 0.6, 0.8, 1.0],
    labels=["Crítico", "Baixo", "Moderado", "Alto"]
)

# (Opcional) Remove linhas onde o IFDM ou faixa não foi encontrado
sinasc_raw = sinasc_raw.dropna(subset=["IFDM", "faixa_IFDM"])

# Exibe uma amostra para conferir as colunas adicionadas
print(sinasc_raw[["munResNome", "IFDM", "faixa_IFDM"]].drop_duplicates().sort_values("IFDM"))

                      munResNome   IFDM faixa_IFDM
517                   Corumbiara  0.541      Baixo
198                Costa Marques  0.552      Baixo
11425                     Cabixi  0.568      Baixo
736    Governador Jorge Teixeira  0.573      Baixo
3068                   Theobroma  0.574      Baixo
1801                Seringueiras  0.575      Baixo
73                       Cujubim  0.576      Baixo
174                Vale do Anari  0.579      Baixo
0          Alta Floresta D'Oeste  0.579      Baixo
119                   Rio Crespo  0.586      Baixo
200       Campo Novo de Rondônia  0.587      Baixo
125                  Cacaulândia  0.587      Baixo
1411    São Francisco do Guaporé  0.589      Baixo
1509    Nova Brasilândia D'Oeste  0.589      Baixo
2132                 Chupinguaia  0.590      Baixo
178           Candeias do Jamari  0.590      Baixo
259           Machadinho D'Oeste  0.593      Baixo
3558               Teixeirópolis  0.597      Baixo
2067                Castanheiras  0.598      Baixo
1401                     Parecis  0.598      Baixo
75                  Alto Paraíso  0.598      Baixo
1292           Presidente Médici  0.599      Baixo
77                   Monte Negro  0.599      Baixo
3566             Vale do Paraíso  0.599      Baixo
1427          Ministro Andreazza  0.601   Moderado
1782       Primavera de Rondônia  0.601   Moderado
138                      Buritis  0.601   Moderado
3        Alto Alegre dos Parecis  0.602   Moderado
594        São Miguel do Guaporé  0.603   Moderado
348            Colorado do Oeste  0.607   Moderado
360                  Nova Mamoré  0.610   Moderado
2555               Guajará-Mirim  0.611   Moderado
83                          Jaru  0.612   Moderado
1194                  Cerejeiras  0.613   Moderado
1087            Mirante da Serra  0.613   Moderado
72                     Ariquemes  0.623   Moderado
4045        Pimenteiras do Oeste  0.627   Moderado
6        Novo Horizonte do Oeste  0.628   Moderado
1406             Espigão D'Oeste  0.635   Moderado
435          Ouro Preto do Oeste  0.639   Moderado
132                    Ji-Paraná  0.645   Moderado
839                Pimenta Bueno  0.647   Moderado
21                Rolim de Moura  0.648   Moderado
1381                      Cacoal  0.654   Moderado
141                      Vilhena  0.671   Moderado
123                  Porto Velho  0.674   Moderado

### 5.3 PIB
C - https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_Rond%C3%B4nia_por_PIB

In [66]:
pib_dict = {
    "Porto Velho": 20059.522,
    "Ji-Paraná": 4231.113,
    "Vilhena": 4215.046,
    "Ariquemes": 3209.761,
    "Cacoal": 2792.383,
    "Jaru": 1765.089,
    "Pimenta Bueno": 1642.516,
    "Rolim de Moura": 1565.194,
    "Guajará-Mirim": 1054.179,
    "Ouro Preto do Oeste": 985.868,
    "Buritis": 966.552,
    "São Miguel do Guaporé": 905.335,
    "Machadinho D'Oeste": 890.320,
    "Espigão D'Oeste": 773.381,
    "Cerejeiras": 743.037,
    "Nova Mamoré": 742.687,
    "Alta Floresta D'Oeste": 734.469,
    "Candeias do Jamari": 655.606,
    "Presidente Médici": 559.990,
    "Nova Brasilândia D'Oeste": 548.734,
    "Alto Paraíso": 510.361,
    "São Francisco do Guaporé": 488.043,
    "Cujubim": 487.480,
    "Alto Alegre dos Parecis": 483.672,
    "Chupinguaia": 468.793,
    "Colorado do Oeste": 424.807,
    "Corumbiara": 396.728,
    "Monte Negro": 389.891,
    "Campo Novo de Rondônia": 369.377,
    "Alvorada D'Oeste": 352.628,
    "Seringueiras": 332.987,
    "Costa Marques": 316.671,
    "Ministro Andreazza": 297.878,
    "Cacaulândia": 275.338,
    "Urupá": 273.501,
    "Mirante da Serra": 262.640,
    "Theobroma": 257.426,
    "Pimenteiras do Oeste": 246.209,
    "Governador Jorge Teixeira": 239.330,
    "Cabixi": 238.412,
    "Novo Horizonte do Oeste": 231.502,
    "Vale do Anari": 220.588,
    "Santa Luzia D'Oeste": 213.556,
    "Itapuã do Oeste": 210.031,
    "Vale do Paraíso": 185.648,
    "Rio Crespo": 184.430,
    "Nova União": 157.321,
    "Parecis": 155.434,
    "São Felipe D'Oeste": 130.676,
    "Teixeirópolis": 121.301,
    "Primavera de Rondônia": 107.030,
    "Castanheiras": 99.627
}

In [77]:
# Adiciona a coluna PIB no dataframe 
sinasc_raw["PIB"] = sinasc_raw["munResNome"].map(pib_dict)

# Remove linhas sem correspondência de município
sinasc_raw = sinasc_raw.dropna(subset=["PIB"])

# Exibe confirmação 
print(sinasc_raw[["munResNome", "PIB"]].drop_duplicates().sort_values("PIB").head(10))

                      munResNome      PIB
2067                Castanheiras   99.627
1782       Primavera de Rondônia  107.030
3558               Teixeirópolis  121.301
1401                     Parecis  155.434
119                   Rio Crespo  184.430
3566             Vale do Paraíso  185.648
174                Vale do Anari  220.588
6        Novo Horizonte do Oeste  231.502
11425                     Cabixi  238.412
736    Governador Jorge Teixeira  239.330

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados.

- **Regiões com maior PIB e IDH**, como **Porto Velho e Vilhena**, concentram mães ligeiramente mais velhas e com melhores indicadores de parto (maior APGAR), sugerindo melhores condições socioeconômicas e de saúde.

- **Municípios de menor altitude e área** mostram **maior média de filhos vivos**, o que pode refletir contextos mais rurais e famílias maiores.

- Apesar das diferenças econômicas (PIB, IFDM), **a idade média das mães permanece estável entre as regiões**, indicando que fatores culturais podem ter mais peso que os econômicos na decisão de ter filhos.